# Wait for all coverage jobs before computing status
codecov:
  notify:
    after_n_builds: 8

# Only comment when the coverage numbers actually move
comment:
  after_n_builds: 8
  require_changes: true

ignore:
  - "tests"
  - "examples"
  - "book"
  - "docs"
  - "test_package"
  - "fuzz"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
