---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
  metrics:
    enabled: true
  coverage:
    enabled: false
  cppcheck:
    enabled: true
    options:
      suppress:
        - missingIncludeSystem

languages:

ignore:
  - "style"

exclude_paths:
  - "fuzz/**/*"
  - "fuzz/*"
  - "scripts/**/*"
  - "scripts/*"
  - "**.md"
