load("@rules_cc//cc:defs.bzl", "cc_library")
cc_library(
    name = "cli11",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.hpp"]),
    defines = ["CLI11_COMPILE", "CLI11_ENABLE_EXTRA_VALIDATORS=1"],
    strip_include_prefix = "/include",
    visibility = ["//visibility:public"],
)

# Header-only mode, like the CMake target without CLI11_PRECOMPILED
cc_library(
    name = "cli11_header_only",
    hdrs = glob(["include/**/*.hpp"]),
    strip_include_prefix = "/include",
    visibility = ["//visibility:public"],
)
